spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: '*'
